/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioSources: typeof import('./src/components/AudioSources.vue')['default']
    HomepageHero: typeof import('./src/components/HomepageHero.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuHeader: typeof import('./src/components/MenuHeader.vue')['default']
    Renderer: typeof import('./src/components/Renderer.vue')['default']
  }
}
